/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PastorsRouteImport } from './routes/pastors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'

const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PastorsRoute = PastorsRouteImport.update({
  id: '/pastors',
  path: '/pastors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pastors': typeof PastorsRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/speakers': typeof SpeakersRoute
  '/resources/$slug': typeof ResourcesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pastors': typeof PastorsRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/speakers': typeof SpeakersRoute
  '/resources/$slug': typeof ResourcesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pastors': typeof PastorsRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/speakers': typeof SpeakersRoute
  '/resources/$slug': typeof ResourcesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pastors'
    | '/resources'
    | '/schedule'
    | '/speakers'
    | '/resources/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pastors'
    | '/resources'
    | '/schedule'
    | '/speakers'
    | '/resources/$slug'
  id:
    | '__root__'
    | '/'
    | '/pastors'
    | '/resources'
    | '/schedule'
    | '/speakers'
    | '/resources/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PastorsRoute: typeof PastorsRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ScheduleRoute: typeof ScheduleRoute
  SpeakersRoute: typeof SpeakersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pastors': {
      id: '/pastors'
      path: '/pastors'
      fullPath: '/pastors'
      preLoaderRoute: typeof PastorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PastorsRoute: PastorsRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  ScheduleRoute: ScheduleRoute,
  SpeakersRoute: SpeakersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
